# Generated by Django 4.2.9 on 2024-01-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adsc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotClientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="ф.и.о.")),
                ("first_name", models.CharField(max_length=150, verbose_name="ф.и.о.")),
                (
                    "phone",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="номер телефона"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="имейл"
                    ),
                ),
                (
                    "adv_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="adsc.advertcompany",
                    ),
                ),
            ],
        ),
    ]
